// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHkDn-iHPo4QFl1bVcqB4z5cN7v0u7Uys',
    appId: '1:826751105361:web:b169d79aea16c3de32bb70',
    messagingSenderId: '826751105361',
    projectId: 'mob-13n14',
    authDomain: 'mob-13n14.firebaseapp.com',
    databaseURL: 'https://mob-13n14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mob-13n14.firebasestorage.app',
    measurementId: 'G-K13WVYXVY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtu7d2WR-u5iWL0b_COyr5E3CTNkLtadY',
    appId: '1:826751105361:android:9cf861734ac7b70f32bb70',
    messagingSenderId: '826751105361',
    projectId: 'mob-13n14',
    databaseURL: 'https://mob-13n14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mob-13n14.firebasestorage.app',
  );
}
